@extends('layouts.dashboard')
@section('content')
<div class="row">
  <x-invoice-sidebar/>
  <div class="col-md-10">
    <div class="tabs">
      <ul class="nav nav-tabs tabs-primary">
        <li class="nav-item active">
          <a class="nav-link" href="#overview" data-toggle="tab"><b>Invoice & Payment Management</b></a>
        </li>
      </ul>
      <div class="tab-content">
        <div id="overview" class="tab-pane active">
          <div class="row">
            <div class="col-md-12 mt-3">
              <div class="alert alert-primary">
                @if($page == 'TOTAL')
                List of Invoices generated by Licensee and their payment status.
                @else
                Payment made by Licensee, verification/confirmation by DITC awaited.
                @endif
              </div>
            </div>
          </div>

          <table class="table mt-4 table-striped table-responsive" id="totalInvoiceTable">
            <thead>
              <tr>
                <th>#</th>
                <th>Challan #</th>
                <th>Licensee Name #</th>
                <th>Annual Charges</th>
                <th>One Time Charges</th>
                <th>Total</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              @if($invoices->count())
              @foreach($invoices as $item)
              <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $item->challan_no }}</td>
                <td>{{ $item->rowUser->name }}</td>
                <td>Rs. {{ $item->total_annual_charge }}</td>
                <td>Rs. {{ $item->total_ot_charge }}</td>
                <td>Rs. {{ $item->total_payable }}</td>
                @if($item->status == "PENDING")
                <td style="color:red;">{{$item->status}}</td>
                <td>
                  <a href="{{route('paymentStatus', $item->challan_no )}}" class="btn btn-dark btn-sm"> Verify</a>
                </td>
                @elseif($item->status == "ACTIVE")
                <td style="color:green;">{{$item->status}}</td>
                <td>
                  <button type="button" name="button">No actions available</button>
                </td>
                @elseif($item->status == "PAID")
                <td style="color:green;">{{$item->status}}</td>
                <td>
                  <button type="button" name="button">No actions available</button>
                </td>
                @endif
                <!-- <td>
                  <a href="{{route('paymentStatus', $item->challan_no )}}" class="btn btn-dark btn-sm"> Verify</a>
                </td> -->
              </tr>
              @endforeach
              @else
              <tr>
                <td colspan="6">No Data available</td>
              </tr>
              @endif
            </tbody>
          </table>
          {{$invoices->links()}}
          </div>
        </div>
      </div>
    </div>
</div>

  @endsection
